name: Tekton inside Github Actions

# Controls when the workflow will run
on:
  push:
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  run-pipeline:
    name: Run Pipeline
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: engineerd/setup-kind@v0.5.0
      - run: |
          export KUBECONFIG="$(kind get kubeconfig-path)"
          kubectl apply --filename https://storage.googleapis.com/tekton-releases/pipeline/latest/release.yaml
      - uses: jerop/tkn@v0.1.0

      - name: Show Tekton tasks and pipelines
        run: |
          tkn task list --all-namespaces
          tkn pipeline list --all-namespaces
